apiVersion : apps/v1beta2
kind: Deployment
metadata:
  name: "kubeglen-9595"
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: "kubeglen-9595"
    spec:
      containers:
        - name: "kubeglen-9595"
          image: "kubeglen.azurecr.io/kubeglen"
          ports:
          - containerPort: 80
