apiVersion: v1
kind: Service
metadata:
    name: "kubeglen-9595"
    labels:
        app: "kubeglen-9595"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubeglen-9595"