on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: kubeglen.azurecr.io
        username: ${{ secrets.acr_kubeglen_username }}
        password: ${{ secrets.acr_kubeglen_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t kubeglen.azurecr.io/kubeglen:${{ github.sha }}
        docker push kubeglen.azurecr.io/kubeglen:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_kubeglen_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep kubeglen99aa | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace kubeglen99aa`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: kubeglen99aa
        container-registry-url: kubeglen.azurecr.io
        container-registry-username: ${{ secrets.acr_kubeglen_username }}
        container-registry-password: ${{ secrets.acr_kubeglen_password }}
        secret-name: kubeglendockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: kubeglen99aa
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
        images: |
          kubeglen.azurecr.io/kubeglen:${{ github.sha }}
        imagepullsecrets: |
          kubeglendockerauth